### ISSUE TITLE
Arrange the incoming Github profile in ascending order 

### ISSUE THREAD

**Issue by ayush015** [ayush015/Github-Compare#1]
As when you setup the project and run you will see a search bar where you can search your github username and get a card will appear with these following details 

Your Github username , avatar, name, followers ,following ,public Repo's and public gists

what is needed, arrange the incoming profile in ascending order either on the basis of number of followers or following
make sure when you search new username its should be sorted according to the given condition
![Screenshot 2020-10-14 at 5 21 26 PM](https://user-images.githubusercontent.com/36740639/95985054-b955c080-0e41-11eb-9540-1a4b05caa590.png)
 Go through [CONTRIBUTING.md](https://github.com/ayush015/Github-Compare/blob/master/CONTRIBUTING.md)

**Comment by aksharadyuti** [comment]
I would like to try. Could you assign this to me?

**Comment by ayush015** [comment]
@aksharadyuti Sure go ahead :)

**Comment by dimitrov-d** [comment]
I have resolved this here #2 
Sorry, I already started to work on it today but forgot to mention it here in the issue

**Comment by ayush015** [comment]
@dimitrov-d  its totally cool . Let me go through both the PR . And Can you add a screenshot supporting your PR #2

**Comment by ayush015** [comment]
@aksharadyuti any word ? 
I will be merging #2 PR in a short while
